name:                prolog-graph-lib
version:             0.3.0.0
synopsis:            Generating images of resolution trees for Prolog queries.
description:         This is the library part (See <http://hackage.haskell.org/package/prolog-graph> for the command line tool).
license:             PublicDomain
author:              Matthias Bartsch
maintainer:          Oliver Westphal (oliver.westphal <at> uni-due.de)
category:            Language
build-type:          Simple
github:              fmidue/prolog-graph-lib

dependencies:
  - base >=4 && <5
  - prolog >= 0.2.1
  - fgl >= 5.4.2.4
  - mtl >= 2.0.1.0
  - text >= 0.11.1.5
  - graphviz >= 2999.12.0.3
  - bytestring

ghc-options:
  - -Wall

library:
  source-dirs: src
  exposed-modules:
    - Language.Prolog.GraphViz

executables:
  prolog-graph:
    source-dirs: prolog-graph
    main: Main.hs
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prolog-graph-lib
    - cmdargs >= 0.8


