resolver: lts-19.24

packages:
- .

extra-deps:
- git: https://github.com/fmidue/prolog
  commit: feb3b1e3e806e30ce9346046f8e9239c199888df
- fgl-5.8.1.1
- graphviz-2999.20.1.0 # needed for newest revision
