resolver: lts-19.24

packages:
- .

extra-deps:
- git: https://github.com/fmidue/prolog
  commit: 700a1f79c1439ed98798c2576a0770d78f14d964
- fgl-5.8.1.1
- graphviz-2999.20.1.0 # needed for newest revision
