resolver: lts-19.24

packages:
- .

extra-deps:
- git: https://github.com/fmidue/prolog
  commit: 0bac2c937602c13ba3a7f061795350c320f41254
- fgl-5.8.1.1
- graphviz-2999.20.1.0 # needed for newest revision
