resolver: lts-19.24

packages:
- .

extra-deps:
- git: https://github.com/fmidue/prolog
  commit: ae553c07eab85b3e64e5ce85eaac991f1df12499
- fgl-5.8.1.1
- graphviz-2999.20.1.0 # needed for newest revision
